---
- name: Manage Vagrant User and SELinux Context
  hosts: all
  become: yes
  gather_facts: no
  vars:
    ansible_password: $6$xOpWRIeHhJJgiOFX$80Fbjj80ERdC4XAXQdl8o/uGZ9rk8wJv6v9u.DI7qeiEnlKLT7GpJMxQbaLVh3MMgj.l.Hjgoj2kn0F4v0hyP1
  tasks:
    - name: Ensure vagrant user exists
      ansible.builtin.user:
        name: alice
        state: present
        createhome: yes
        password: "{{ ansible_password }}"

    - name: Install policycoreutils-python-utils package (if needed)
      ansible.builtin.package:
        name: policycoreutils-python-utils
        state: present

    - name: Add SELinux login mapping for vagrant user
      ansible.builtin.command:
        cmd: semanage login -a -s user_u vagrant
      register: semanage_login_result
      failed_when: semanage_login_result.rc not in [0, 1]
      changed_when: semanage_login_result.rc == 0

    - name: Add SELinux file context for vagrant home directory
      ansible.builtin.command:
        cmd: semanage fcontext -a -t user_home_dir_t "/home/vagrant(/.*)?"
      register: semanage_fcontext_result
      failed_when: semanage_fcontext_result.rc not in [0, 1]
      changed_when: semanage_fcontext_result.rc == 0

    - name: Restore SELinux context on vagrant home directory
      ansible.builtin.command:
        cmd: restorecon -R -v /home/vagrant
