---
- name: Manage Vagrant User and SELinux Context
  hosts: all
  become: yes
  gather_facts: no
  vars:
    ansible_password: $6$xOpWRIeHhJJgiOFX$80Fbjj80ERdC4XAXQdl8o/uGZ9rk8wJv6v9u.DI7qeiEnlKLT7GpJMxQbaLVh3MMgj.l.Hjgoj2kn0F4v0hyP1
  tasks:
    - name: Ensure vagrant user exists
      ansible.builtin.user:
        name: alice
        state: present
        createhome: yes
        password: "{{ ansible_password }}"
