---
- name: Manage SSH keys
  hosts: "{{ target_host | default('all') }}"
  become: yes
  vars:
    user: "{{ user_name }}"

  tasks:
    - name: Ensure .ssh directory exists
      ansible.builtin.file:
        path: "/home/{{ user }}/.ssh"
        state: directory
        mode: '0700'
        owner: "{{ user }}"
        group: "{{ user }}"

    - name: Copy authorized_keys file
      ansible.builtin.copy:
        src: /home/vagrant/.ssh/authorized_keys
        dest: "/home/{{ user }}/.ssh/authorized_keys"
        mode: '0600'
        owner: "{{ user }}"
        group: "{{ user }}"
        remote_src: yes

    - name: Ensure SELinux context is correct for .ssh directory
      ansible.builtin.file:
        path: "/home/{{ user }}/.ssh"
        state: directory
        setype: ssh_home_t
      when: ansible_selinux.status == "enabled"
