---
- name: Setup Alice User
  hosts: all
  become: yes

  roles:
    - role: user_setup  # Include the manage_ssh role here.
      vars:
        user: alice  # Pass the username to the role.       target_host: "{{ inventory_hostname }}"
        # password: "{{ ansible_password }}"
