---
- name: Install and Configure Cockpit
  hosts: all,localhost
  become: yes  # This ensures the tasks run with root privileges
  tasks:
    # - name: Search for Cockpit packages
    #   ansible.builtin.command:
    #     cmd: dnf search cockpit
    #   register: cockpit_search
    #   changed_when: false  # This command doesn't change the system state

    # - name: Display Cockpit search results
    #   ansible.builtin.debug:
    #     var: cockpit_search.stdout_lines

    - name: Install Cockpit and Cockpit SELinux module
      ansible.builtin.dnf:
        name:
          - cockpit
          - cockpit-selinux
        state: present

    - name: Start Cockpit service
      ansible.builtin.systemd:
        name: cockpit
        state: started
        enabled: yes  # This ensures Cockpit starts on boot

